# Generated by Django 3.2.3 on 2021-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.CharField(default='some string', max_length=100),
        ),
    ]
